'use strict';

// T4 — Migration idempotency CLI test.
//
// Verifies that running `convoke-migrate --apply --force` twice doesn't
// break state. `scripts/migrate-artifacts.js:278` (`detectMigrationState`)
// implements idempotent recovery: if the previous migration is complete and
// no new ungoverned files exist, the second run exits cleanly with
// "Nothing to migrate" and makes no new commits.
//
// Existing coverage: unit tests cover `parseArgs` and `detectMigrationState`
// in isolation. This suite closes the gap at the CLI integration level:
// the full `convoke-migrate` child-process flow against a real git repo.

const { describe, it, before, after } = require('node:test');
const assert = require('node:assert/strict');
const path = require('path');
const fs = require('fs-extra');
const os = require('os');
const { execSync } = require('child_process');

const { runScript, PACKAGE_ROOT } = require('../helpers');

const MIGRATE_SCRIPT = path.join(PACKAGE_ROOT, 'scripts/migrate-artifacts.js');

function git(cwd, cmd) {
  return execSync(`git ${cmd}`, { cwd, stdio: 'pipe', encoding: 'utf8' });
}

// Seed a minimal Convoke-shaped project: git-initialized, one ungoverned
// planning artifact using the legacy `type-initiative` convention that the
// migration should rewrite to `initiative-type`.
async function seedProject(tmpDir) {
  git(tmpDir, 'init -q');
  git(tmpDir, 'config user.email test@convoke.test');
  git(tmpDir, 'config user.name "Convoke T4 Test"');
  // Node's execSync can't set `-c commit.gpgsign=false` per-invocation
  // portably across git versions; set it at repo level.
  git(tmpDir, 'config commit.gpgsign false');

  // `findProjectRoot` walks up looking for a `_bmad/` dir — create it so the
  // CLI recognizes the tmp dir as a Convoke project.
  await fs.ensureDir(path.join(tmpDir, '_bmad'));

  const planning = path.join(tmpDir, '_bmad-output/planning-artifacts');
  await fs.ensureDir(planning);

  // Seed an ungoverned file in legacy format. "gyre" is a platform initiative;
  // "prd" is a canonical artifact_type. Migration should rename
  //   prd-gyre.md  →  gyre-prd.md
  // and inject frontmatter + generate an ADR.
  await fs.writeFile(
    path.join(planning, 'prd-gyre.md'),
    '# Gyre PRD\n\nSeeded by T4 fixture.\n',
    'utf8'
  );

  // Initial commit so `detectMigrationState` has a git log to read.
  git(tmpDir, 'add -A');
  git(tmpDir, 'commit -q -m "seed: ungoverned gyre PRD"');
}

function gitLogCount(cwd) {
  return parseInt(git(cwd, 'rev-list --count HEAD').trim(), 10);
}

describe('convoke-migrate CLI idempotency (T4)', () => {
  let tmpDir;
  let commitsAfterFirstRun;

  before(async () => {
    tmpDir = await fs.mkdtemp(path.join(os.tmpdir(), 'convoke-t4-migrate-'));
    await seedProject(tmpDir);
  });

  after(async () => {
    await fs.remove(tmpDir);
  });

  it('first run renames ungoverned file and creates migration commits', async () => {
    const baselineCommits = gitLogCount(tmpDir);
    assert.equal(baselineCommits, 1, 'fixture should start with exactly 1 commit');

    const result = await runScript(MIGRATE_SCRIPT, ['--apply', '--force'], { cwd: tmpDir, timeout: 60000 });
    assert.equal(result.exitCode, 0, `first migrate run must exit 0\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`);

    // File renamed to governance convention.
    const newPath = path.join(tmpDir, '_bmad-output/planning-artifacts/gyre-prd.md');
    const oldPath = path.join(tmpDir, '_bmad-output/planning-artifacts/prd-gyre.md');
    assert.ok(fs.existsSync(newPath), 'gyre-prd.md must exist after migration');
    assert.ok(!fs.existsSync(oldPath), 'prd-gyre.md must no longer exist');

    // At least one new migration commit landed (rename phase, injection phase).
    commitsAfterFirstRun = gitLogCount(tmpDir);
    assert.ok(commitsAfterFirstRun > baselineCommits, `migration must create commits (baseline=${baselineCommits}, after=${commitsAfterFirstRun})`);
  });

  it('second run with identical state exits 0 and reports an idempotent no-op', async () => {
    const result = await runScript(MIGRATE_SCRIPT, ['--apply', '--force'], { cwd: tmpDir, timeout: 60000 });
    assert.equal(result.exitCode, 0, `second run must exit 0\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`);
    // The CLI emits one of these on a clean re-run:
    //   - "Nothing to migrate" (state === 'complete' AND manifest has no work)
    //   - "Nothing to rename" (state === 'complete' but manifest flags leftover
    //     meta-artifacts like the ADR + rename-map generated by the first run)
    // Either satisfies functional idempotency — the `no-new-commits` test below
    // is the hard proof.
    assert.match(
      result.stdout,
      /Nothing to (migrate|rename)/i,
      `second run should report a no-op state — got:\n${result.stdout}`
    );
  });

  it('second run creates no new git commits (idempotency proof)', () => {
    const commitsAfterSecondRun = gitLogCount(tmpDir);
    assert.equal(
      commitsAfterSecondRun,
      commitsAfterFirstRun,
      `second run must not add commits (after first=${commitsAfterFirstRun}, after second=${commitsAfterSecondRun})`
    );
  });

  it('third run after adding a new ungoverned file resumes migration', async () => {
    const newFile = path.join(tmpDir, '_bmad-output/planning-artifacts/epic-gyre.md');
    await fs.writeFile(newFile, '# New Gyre Epic\n\nAdded after first migration.\n', 'utf8');
    git(tmpDir, 'add -A');
    git(tmpDir, 'commit -q -m "seed: add ungoverned epic after migration"');

    const commitsBefore = gitLogCount(tmpDir);
    const result = await runScript(MIGRATE_SCRIPT, ['--apply', '--force'], { cwd: tmpDir, timeout: 60000 });
    assert.equal(result.exitCode, 0, `third run must exit 0\nstdout:\n${result.stdout}\nstderr:\n${result.stderr}`);

    // New file should be renamed to governance convention.
    const migratedPath = path.join(tmpDir, '_bmad-output/planning-artifacts/gyre-epic.md');
    const origPath = path.join(tmpDir, '_bmad-output/planning-artifacts/epic-gyre.md');
    assert.ok(fs.existsSync(migratedPath), 'gyre-epic.md must exist after third run');
    assert.ok(!fs.existsSync(origPath), 'epic-gyre.md must no longer exist');

    const commitsAfter = gitLogCount(tmpDir);
    assert.ok(commitsAfter > commitsBefore, `third run must create new commits when ungoverned files exist (before=${commitsBefore}, after=${commitsAfter})`);
  });
});
